# Generated by Django 4.2.7 on 2026-01-04 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_message_notifications', models.BooleanField(default=True, verbose_name='Уведомления о новых сообщениях')),
                ('receive_course_notifications', models.BooleanField(default=True, verbose_name='Уведомления о новых материалах курсов')),
                ('receive_system_notifications', models.BooleanField(default=True, verbose_name='Системные уведомления')),
                ('enable_push_notifications', models.BooleanField(default=False, verbose_name='Включить push-уведомления')),
                ('push_token', models.CharField(blank=True, max_length=255, verbose_name='Токен для push-уведомлений')),
                ('last_notification_check', models.DateTimeField(auto_now=True, verbose_name='Последняя проверка уведомлений')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройка уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_message', 'Новое сообщение'), ('new_course_material', 'Новый материал курса'), ('chat_invitation', 'Приглашение в чат'), ('course_attached', 'Курс прикреплён к чату'), ('registration_approved', 'Регистрация подтверждена'), ('registration_rejected', 'Регистрация отклонена'), ('password_reset', 'Сброс пароля'), ('system_announcement', 'Системное объявление')], max_length=50, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('related_model', models.CharField(blank=True, max_length=100, verbose_name='Связанная модель')),
                ('related_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID связанного объекта')),
                ('status', models.CharField(choices=[('unread', 'Не прочитано'), ('read', 'Прочитано'), ('archived', 'В архиве')], default='unread', max_length=20, verbose_name='Статус')),
                ('send_push', models.BooleanField(default=False, verbose_name='Отправить push-уведомление')),
                ('push_sent', models.BooleanField(default=False, verbose_name='Push отправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='notificatio_user_id_cd4f27_idx'), models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_f77590_idx')],
            },
        ),
    ]
