# Generated by Django 4.2.7 on 2026-01-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsettings',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_cd4f27_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_f77590_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='push_sent',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='read_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_model',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='send_push',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_chat_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_course_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_chat', 'Добавлен в чат'), ('new_course_material', 'Новый материал в курсе'), ('course_attached', 'Курс прикреплён к чату'), ('registration_approved', 'Регистрация подтверждена'), ('registration_rejected', 'Регистрация отклонена'), ('system', 'Системное уведомление')], max_length=50, verbose_name='Тип уведомления'),
        ),
        migrations.DeleteModel(
            name='NotificationSettings',
        ),
    ]
