FROM node:20-slim

WORKDIR /app

# Копируем зависимости
COPY package*.json ./

# Устанавливаем ВСЕ зависимости (включая devDependencies!)
RUN npm install

# Копируем весь код
COPY . .

EXPOSE 3000

# Запускаем dev-сервер
CMD ["npm", "run", "dev"]