# Generated by Django 5.2.9 on 2026-01-01 15:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_department_code_alter_department_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название курса', max_length=200, verbose_name='Название курса')),
                ('short_description', models.TextField(blank=True, help_text='Краткое описание курса (до 500 символов)', verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, help_text='Подробное описание курса', verbose_name='Полное описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(help_text='Преподаватель или директор, создавший курс', limit_choices_to={'role__in': ['teacher', 'director']}, on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='Автор курса')),
                ('department', models.ForeignKey(help_text='Департамент, к которому относится курс', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название модуля', max_length=200, verbose_name='Название модуля')),
                ('description', models.TextField(blank=True, help_text='Описание содержания модуля', verbose_name='Описание модуля')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядковый номер модуля в курсе', verbose_name='Порядок')),
                ('course', models.ForeignKey(help_text='Курс, к которому относится модуль', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Модуль курса',
                'verbose_name_plural': 'Модули курса',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название материала', max_length=200, verbose_name='Название материала')),
                ('material_type', models.CharField(choices=[('article', 'Статья'), ('presentation', 'Презентация'), ('video', 'Видео'), ('other', 'Другой материал')], default='article', help_text='Выберите тип материала', max_length=20, verbose_name='Тип материала')),
                ('content', models.TextField(blank=True, help_text='Текстовое описание или содержание материала', verbose_name='Текстовое содержание')),
                ('file', models.FileField(blank=True, help_text='Загрузите файл материала', null=True, upload_to='course_materials/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt', 'rtf', 'odt', 'ppt', 'pptx', 'odp', 'key', 'mp4', 'avi', 'mov', 'wmv', 'flv', 'mkv', 'webm', 'jpg', 'jpeg', 'png', 'gif', 'bmp', 'svg', 'zip', 'rar', '7z'])], verbose_name='Файл')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядковый номер материала в модуле', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('module', models.ForeignKey(help_text='Модуль, к которому относится материал', on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Материал курса',
                'verbose_name_plural': 'Материалы курса',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-created_at'], name='courses_cou_created_c141ec_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['author'], name='courses_cou_author__d9595f_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['department'], name='courses_cou_departm_93b58f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('module', 'order')},
        ),
    ]
