# Generated by Django 4.2.7 on 2026-01-09 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresetcode'),
        ('courses', '0002_remove_module_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Департамент, к которому относится курс', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.department', verbose_name='Департамент'),
        ),
    ]
