# Generated by Django 5.2.9 on 2025-12-26 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название чата')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_chats', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='users.department', verbose_name='Департамент')),
                ('study_groups', models.ManyToManyField(related_name='chats', to='users.studygroup', verbose_name='Учебные группы')),
                ('teachers', models.ManyToManyField(limit_choices_to={'role': 'teacher'}, related_name='teaching_chats', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватели')),
            ],
            options={
                'verbose_name': 'Учебный чат',
                'verbose_name_plural': 'Учебные чаты',
                'ordering': ['-created_at'],
            },
        ),
    ]
