# Generated by Django 4.2.7 on 2026-01-12 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название раздела')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(limit_choices_to={'chat_type': 'group'}, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='chats.chat', verbose_name='Чат')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_sections', to=settings.AUTH_USER_MODEL, verbose_name='Создатель раздела')),
            ],
            options={
                'verbose_name': 'Раздел чата',
                'verbose_name_plural': 'Разделы чатов',
                'ordering': ['order', 'created_at'],
                'unique_together': {('chat', 'name')},
            },
        ),
        migrations.AddField(
            model_name='message',
            name='section',
            field=models.ForeignKey(default=1, help_text='Cообщение будет относиться к конкретному разделу', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chatsection', verbose_name='Раздел'),
        ),
    ]
