# Generated by Django 4.2.7 on 2026-02-04 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_chatsection_message_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, help_text='Для учебных чатов: название дисциплины. Для личных: автоматически генерируется', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('role', 'teacher'), ('role', 'director'), _connector='OR'), related_name='teaching_chats', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватели'),
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to='message_attachments/%Y/%m/%d/', verbose_name='Файл')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('file_type', models.CharField(choices=[('document', 'Документ'), ('image', 'Изображение'), ('video', 'Видео'), ('audio', 'Аудио'), ('archive', 'Архив'), ('other', 'Другой')], default='document', max_length=20, verbose_name='Тип файла')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер файла (байты)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chats.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Прикрепленный файл',
                'verbose_name_plural': 'Прикрепленные файлы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
